version: '3'

services:
  mysqldb:
    container_name: mysql
    image: mysql
    ports:
      - "3307:3306"
    environment: 
      MYSQL_ROOT_PASSWORD : 123456
    networks:
      - draw
    volumes:
      - .\\mysql_data:/var/lib/mysql

  mongodb:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
    networks:
      - draw
    volumes:
      - .\\mongo_data:/data/db


  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASS=<password>
    networks:
      - draw
      
  
  drawapinode:
    container_name: drawapinode
    image: drawapinode
    environment:
      - PORT=3000
      - NODE_ENV=production
      - DB_TYPE=nosql
      - MONGODB_CSTR=mongodb://mongodb:27017/drawdbnode
      - DBHOST=mysqldb
      - DBUSERNAME=root
      - DBPASSWORD=123456
      - DBNAME=drawdbnode
      - DBDIALECT=mysql
      - AUTORIZE_SECRET_KEY=<token-secret-key>
      - REDIS_URL=redis://default:<password>@redis:6379
      - GEOSERVICE_URL=https://drawprogram.org/geo/
    ports:
      - '3000:3000'
    networks:
      - draw


networks:
  draw:
    driver: bridge



